### ISSUE TITLE
Add checks for NELM break

### ISSUE THREAD

**Issue by zhubonan** [kavanase/vaspup2.0#1]
When NELM is breached the resulting energies cannot be used for convergence testing. Checks should be added to warn the user if that is the case.

**Comment by kavanase** [comment]
Resolved and tested in commits 863146b1ad927ca2b3b176ab6875dbc66439fc07, b7adb2acd9a49e9b25e76c96483d339ffc0018f5 and f64c9d63adc730b7662bf1e8ea35900287817995.
Thanks for contributing!!

**Comment by zhubonan** [comment]
@kavanase Is the line `electronic self-consistency was not achieved` new for VASP6`?

For VASP5 it does not have this warning and VASP always says `aborting loop because EDIFF is reached` even it is not, but just because NELM is reached. I think the only way is to check for NELM breach is to compare the last `Iteration` number and the `NELM` stated in OUTCAR at the beginning.

**Comment by kavanase** [comment]
You're right! Fixed now (by comparing last iteration number with NELM)
