### ISSUE TITLE
Add magnetisation data

### ISSUE THREAD

**Issue by zhubonan** [kavanase/vaspup2.0#2]
For magnetic systems with poor initial structure/initial MAGMOM, convergence test calculations may end up with different spin arrangements, hence resulting in different energies.

The total magnetisation should be added to the output (if applicable) so the user can see if that is the case and decide how to proceed with the test.

**Comment by kavanase** [comment]
Resolved and tested in commits 863146b1ad927ca2b3b176ab6875dbc66439fc07, b7adb2acd9a49e9b25e76c96483d339ffc0018f5 and f64c9d63adc730b7662bf1e8ea35900287817995.
Thanks for contributing!!
