### ISSUE TITLE
Add functionality for force/stress convergence tests

### ISSUE THREAD

**Issue by zhubonan** [kavanase/vaspup2.0#4]
The total energy is not always a good measure for the quality of the calculation. In particular, VASP apply a POTCAR specific kinetic energy correction such that the total energy may converge slowly/never converge to the required accuracy with increasing cut off energy. 

In practice, the raw DFT energy has no well-defined meaning and the energy difference is actually what matters most. It should converge faster than the total energy by error cancellation. However, the _difference_ not well defined for a single mateiral. 

Forces and the stress are the gradients of the energy and may be used to provide extra insights. Hence it is useful to include them into the convergence tests. Also, the converging the stress allows the Pulay stress to be estimated when using a low cut off is necessary, or allow the relaxation to run with variable cell (ISIF=3).

**Comment by kavanase** [comment]
Thanks for the suggestion @zhubonan, this has now been added in [ef9dcb5](https://github.com/kavanase/vaspup2.0/commit/ef9dcb564fc894b9f460dd2cbad20fa9749ddf16), with example output on the README
